baseurl: /
languageCode: en-us
title: Ecological Network
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: â†©

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Research"
      url: "/research/"
      weight: 3
    - name: "Publications"
      url: "/publications/"
      weight: 4
    - name: "CV"
      url: "/cv/"
      weight: 5
    - name: "Categories"
      url: "/categories/"
      weight: 6
    - name: "Tags"
      url: "/tags/"
      weight: 7
    - name: "Subscribe"
      url: "/index.xml"

params:
  description: "Welcome to my personal website."
  footer: "&copy; [Hai-Dong Li](https://github.com/PrimulaLHD) 2025-{Year} | [Github](https://github.com/PrimulaLHD)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
